freebsd_instance:
  image: freebsd-13-0-release-amd64

task:
  env:
    matrix:
      MRUBY_VERSION: master

  install_script: pkg install -y ruby rubygem-rake bison git
  script:
  - MRUBY_DIR=mruby-${MRUBY_VERSION}
  - fetch -o- https://github.com/mruby/mruby/archive/${MRUBY_VERSION}.zip | tar xf -
  - cd ${MRUBY_DIR}
  - export MRUBY_CONFIG=../.cirrus/build_config.rb
  - rake clean
  - rake -mv test
  - build/host/bin/mruby-gemcut-test
