name: build and test

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  ubuntu-18-04:
    runs-on: ubuntu-18.04
    name: ubuntu-18.04 (mruby-${{matrix.TARGET_MRUBY}})
    strategy:
      matrix:
        TARGET_MRUBY:
        - master
        - 2.1.2
        - 2.1.1
        - 2.1.0
    env:
      MRUBY_URL: "https://github.com/mruby/mruby/archive/${{matrix.TARGET_MRUBY}}.tar.gz"
      MRUBY_DIR: "mruby-${{matrix.TARGET_MRUBY}}"
      MRUBY_CONFIG: "../test_config.rb"
    steps:
    - uses: actions/checkout@v2
    - name: fetch and extract mruby
      run: wget -O- $MRUBY_URL | tar xzf -
    - name: pre-clean
      run: rake -vE "Dir.chdir '$MRUBY_DIR'" clean
    - name: build
      run: rake -mvE "Dir.chdir '$MRUBY_DIR'" || rake -vE "Dir.chdir '$MRUBY_DIR'"
    - name: test
      run: rake -vE "Dir.chdir '$MRUBY_DIR'" test
